version: 2.1
orbs:
  1password: onepassword/secrets@1.0.0
# Define the jobs we want to run for this project
# Define the jobs we want to run for this project
jobs:
  test:
    machine:
        image: ubuntu-2204:current
    steps:
      - checkout
      - 1password/install-cli:
          version: 2.27.0
      - 1password/export:
            var-name: OP_TEST_USERNAME_EXPORT
            secret-reference: op://Test 3/CircleCITest/username
      - 1password/export:
            var-name: OP_TEST_PASSWORD_EXPORT
            secret-reference: op://Test 3/CircleCITest/password
      - 1password/exec:
          command: |
            echo "This value will be masked: $OP_TEST_USERNAME"
            echo "This value will be masked: $OP_TEST_PASSWORD"
      - run:
          command: |
            echo "This value will not be masked: $OP_TEST_USERNAME_EXPORT"
            echo "This value will not be masked: $OP_TES2T_PASSWORD_EXPORT"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
