version: 2.1
orbs:
  1password: onepassword/secrets@1.0.0
# Define the jobs we want to run for this project
jobs:
  test:
    machine:
        image: ubuntu-2204:current
    steps:
      - 1password/install-cli
      - checkout
      - run:
          shell: echo "This value will be masked: $OP_SERVICE_ACCOUNT_TOKEN"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
